FROM node:20 as builder
WORKDIR /app
COPY ./coinis_project ./
RUN npm install
RUN npm run build
# COPY ./entrypoint.server.sh ./
# RUN chmod +x entrypoint.server.sh
# ENTRYPOINT ["ls", "-a"]
# ENTRYPOINT ["bash", "entrypoint.server.sh"]
# CMD [ "npm", "run", "build"]
